### ISSUE TITLE
Issue when I try to join the Server

### ISSUE THREAD

**Issue by eritxo** [Times-0/Timeline#19]
I can Login but when I try to join the server it kicks me.
![imagen](https://user-images.githubusercontent.com/12672332/63956741-4fd0f200-ca87-11e9-943d-d25bc70bb0e2.png)
After that this pop up:
![imagen](https://user-images.githubusercontent.com/12672332/63956659-26b06180-ca87-11e9-84ae-c640e79ea283.png)
(The password is ok)
Here you have the log and the console error.
[TimelineLogs.log](https://github.com/Times-0/Timeline/files/3556448/TimelineLogs.log)
![imagen](https://user-images.githubusercontent.com/12672332/63956607-0c768380-ca87-11e9-9baa-a5e97b51048f.png)
![imagen](https://user-images.githubusercontent.com/12672332/63963514-7c8c0600-ca95-11e9-8647-2b373f04e364.png)

**Comment by valid22** [comment]
Try using this Redis server:
https://github.com/microsoftarchive/redis/releases/download/win-3.0.504/Redis-x64-3.0.504.msi

**Comment by eritxo** [comment]
The Redis version solved it
