### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by RiYANOID** [Times-0/Timeline#2]
[deleted]

**Comment by valid22** [comment]
Can you confirm the `id` column in `friends` table is set as primary and auto-increment?

**Comment by valid22** [comment]
Glad you got things resolved. That error while closing the source is ignore-able, it's because the `redis` client (`TXRedisAPI`) is set to `auto-reconnect`, so as soon as you close Timeline, the connection is lost and it tries to reconnect, which obviously throws some error.

**Comment by valid22** [comment]
> Also, Is there a way to remove membership?

Can you be more clear? If you want to completely remove the membership feature for all players change the following line in `Timeline > Servers > Penguin.py`
```py
self.penguin.member = Membership(self.dbpenguin.membership, self.selfRefer)
```
to
```py
self.penguin.member = Membership(type('MembershipTuple', (object, ), {"timetuple" : lambda : (2017, 1, 1, 1, 1, 1, 1, 1, 1)})(), self.selfRefer)
```

Else if you want to allow certain users Membership and retain non-member accounts at the same time, it's already integrated into the source. 

You just need to set the `membership` column in `penguins` table to the date of expiry of the membership of the respective user.
