### ISSUE TITLE
Not loading the login page

### ISSUE THREAD

**Issue by ColinAA** [Times-0/Timeline#24]
I am using a VPS with ubuntu 18.04, I followed the tutorial step by step and everything seems to be working ( no errors while running etc ). However, when I go to the play domain and click the login button, nothing loads. Flash is enabled and in dev tools everything loads fine ( including clubpenguin.swf). I've tried changing the IP in start.py to 0.0.0.0 and other stuff but nothing seems to work. Thank you.

**Comment by valid22** [comment]
I'm afraid it has nothing to do with the server, I'm closing this issue.
Make sure your ip/port in client matches your server and server is running on the same port with the address `0.0.0.0`
Unless the server receives a message from the client, the server has nothing to do with it and it's probably the clients that's messed up
