### ISSUE TITLE
media1 missing ? 

### ISSUE THREAD

**Issue by The-Real-Thisas** [Times-0/Timeline#30]
I was just following the tutorial when I hit a roadblock, I was installing AS3 and media1 was missing. 

It all happened when I tried to nano the file and it wasn't there.

I went from directory to directory trying to find it and it wasn't there, I honestly couldn't find it anywhere, It may just be me being dumb and not being able to find it or it might have disappeared. 

I just bought a domain just for this and I can't wait to host my own cpps, the guild is well written and pretty good and the code hasn't made me pull my hair out yet.
![Screen Shot 2020-05-01 at 8 28 06 PM](https://user-images.githubusercontent.com/59698123/80821686-4685bf80-8bea-11ea-8571-68bbfedda8ce.png)

**Comment by valid22** [comment]
Use media instead, I'll update the docs soon.

**Comment by The-Real-Thisas** [comment]
Thanks
