### ISSUE TITLE
How is it supposed to be set up? 

### ISSUE THREAD

**Issue by The-Real-Thisas** [Times-0/Timeline#31]
I currently have it on a private server, I don't understand who I'm supposed to link it to my domain as all the https://times-0.github.io/docs show is 
'Then, you add Two CNAME records. one for play subdomain, another for media1/media (AS3/AS2) subdomain. Make sure they look similar to this and save the settings' 
Which makes no sense.
![Screen Shot 2020-05-02 at 12 19 04 AM](https://user-images.githubusercontent.com/59698123/80838626-8a88bc80-8c0a-11ea-9265-521184fb9c60.png)

I don't understand how I'm supposed to link it to my domain. Because Cloudflare requires a Target for the traffic to be transferred to and I don't think I'm supposed to put valid22.pw.
![Screen Shot 2020-05-02 at 12 19 33 AM](https://user-images.githubusercontent.com/59698123/80838661-9b393280-8c0a-11ea-9910-aa79087dcb49.png)

**Comment by valid22** [comment]
`valid22.pw` is an example for the domain name. Name should be `media`, `play`. Target should be your domain name. This is because of recent update in cloudflare, but that's not a big change tho.

**Comment by The-Real-Thisas** [comment]
Oh thank you, I'm really not experienced in this.
