### ISSUE TITLE
Start.py not working

### ISSUE THREAD

**Issue by thePublicer** [Times-0/Timeline#32]
Timeline Logger::Initiated
Starting MySQL DB Pool... @root:timeline
MySQL Database pool setup successfully
Loaded 4 Plugin(s) : Commands, LoginNotification
Player Commands Active!
Login Notification activated!
Firebase initiated
Join(j) Packet handlers initiated!
Login Server::Login initiated!
World Server::Login initiated!
Loaded a fresh set of 28 module(s) in Timeline.Handlers
Loading modules in: Timeline.Handlers
Loaded a fresh set of 8 module(s) in Timeline.PacketHandler
Loading modules in: Timeline.PacketHandler
[LS:Login] Timeline Factory Started!
[LS:Login] Running: Login
[LS:Login] Maximum users: 299
[WS:Gravity] Timeline Factory Started!
[WS:Gravity] Running: Gravity
[WS:Gravity] Maximum users: 299
[WS:Gravity] [Crumbs::Item] Loaded 17 Color Items
[WS:Gravity] [Crumbs::Item] Loaded 1186 Head Items
[WS:Gravity] [Crumbs::Item] Loaded 225 Face Items
[WS:Gravity] [Crumbs::Item] Loaded 311 Neck Items
[WS:Gravity] [Crumbs::Item] Loaded 1529 Body Items
[WS:Gravity] [Crumbs::Item] Loaded 538 Hand Items
[WS:Gravity] [Crumbs::Item] Loaded 315 Feet Items
[WS:Gravity] [Crumbs::Item] Loaded 389 Pin Items
[WS:Gravity] [Crumbs::Item] Loaded 377 Photo Items
[WS:Gravity] [Crumbs::Item] Loaded 36 Award Items
[WS:Gravity] [RoomHandler]  Loaded a total of 81 Room(s)
[WS:Gravity] [RoomHandler]  Loaded 5 Arcade(s)
[WS:Gravity] [RoomHandler]  Loaded 42 Game(s)
[WS:Gravity] [RoomHandler]  Loaded 6 Multiplayer(s)
[WS:Gravity] [RoomHandler]  Loaded 81 Place(s)
Card Jitsu Initiated
Card Jitsu Fire Initiated
FindFour Tables Loaded
Mancala Tables Loaded
Sled Racing' Tracks Initiated
TreasureHunt Tables Loaded
[WS:Gravity] [Crumbs:Post] Loaded 34 Postcard(s)
[WS:Gravity] [Crumbs::Igloo] Loaded 96 Igloo(s)
[WS:Gravity] [Crumbs::Igloo] Loaded 1384 Furniture(s)
[WS:Gravity] [Crumbs::Igloo] Loaded 24 Floor(s)
[WS:Gravity] [Crumbs::Igloo] Loaded 24 Location(s)
[WS:Gravity] [Crumbs::Puffle] Loaded 40 Type of Puffle(s)
[WS:Gravity] [Crumbs::Puffle] Loaded 40 Puffle item(s)
[WS:Gravity] [Crumbs::Stamps] Loaded 352 Stamp(s)
[WS:Gravity] [Crumbs::Stamps] Loaded Stampbook cover details
[WS:Gravity] [Crumbs::Cards] Loaded 509 Card(s)
[WS:Gravity] [Crumbs::Avatar] Loaded 28 Avatar(s)
Engine starting on 6112
Starting factory Login<AS3p+AS2p:1#0>
[LS:Login] Login listening on 127.0.0.1:6112
Engine starting on 9875
Starting factory Gravity<AS3p+AS2p:100#0>
[WS:Gravity] Gravity listening on 127.0.0.1:9875
[LS:Login] (Redis) Setting redis data...
[LS:Login] (Redis) Setup memcache data successful!
[WS:Gravity] (Redis) Setting redis data...
Error executing method - setSensei : an integer is required[exceptions.TypeError: an integer is required in File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__]
*--- Failure #8 ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:501: errback(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:568: _startRunCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:654: _runCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1475: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\maxry\Desktop\Timeline\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:22: setSensei(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\maxry\Desktop\Timeline\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:102: checkForSensei(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:250: inContext(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:266: <lambda>(...)
C:\Python27\lib\site-packages\twisted\python\context.py:122: callWithContext(...)
C:\Python27\lib\site-packages\twisted\python\context.py:85: callWithContext(...)
C:\Python27\lib\site-packages\twistar\dbconfig\mysql.py:26: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:460: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:36: __init__(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:76: reconnect(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:427: connect(...)
C:\Python27\lib\site-packages\MySQLdb\__init__.py:81: Connect(...)
C:\Python27\lib\site-packages\MySQLdb\connections.py:193: __init__(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
exceptions.TypeError: an integer is required
*--- End of Failure #8 ---
[WS:Gravity] (Redis) Setup memcache data successful!
Error executing method - setSensei : an integer is required[exceptions.TypeError: an integer is required in File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__]
*--- Failure #13 ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:501: errback(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:568: _startRunCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:654: _runCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1475: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\maxry\Desktop\Timeline\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:33: setSensei(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\maxry\Desktop\Timeline\Timeline\Database\DB.py:267: db_init(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:250: inContext(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:266: <lambda>(...)
C:\Python27\lib\site-packages\twisted\python\context.py:122: callWithContext(...)
C:\Python27\lib\site-packages\twisted\python\context.py:85: callWithContext(...)
C:\Python27\lib\site-packages\twistar\dbconfig\mysql.py:26: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:460: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:36: __init__(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:76: reconnect(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:427: connect(...)
C:\Python27\lib\site-packages\MySQLdb\__init__.py:81: Connect(...)
C:\Python27\lib\site-packages\MySQLdb\connections.py:193: __init__(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
exceptions.TypeError: an integer is required
*--- End of Failure #13 ---

**Comment by valid22** [comment]
Interesting, what database are you using? Make sure it's mariadb
