### ISSUE TITLE
Can't login to Timeline

### ISSUE THREAD

**Issue by TheRasPiGuy** [Times-0/Timeline#33]
~~Already set up Firebase, but whenever I try to login using Google, it just says "Unable to login. Please relogin. Signin status: Signed-Out", and I can't make an email account, because the Sign Up button does nothing~~

EDIT: The previous issue has been sorted out by adding my server's ip to the host variable at the bottom of Flex.py, but now I am getting multiple other issues, including "auth.failed: database error", "database.error: error verifying user", "OperationalError: Column 'swid' cannot be null"

**Comment by valid22** [comment]
I would suggest discussing this as TimeFlex' issue.
