### ISSUE TITLE
Clicking "Play CPPS" doesn't load the game

### ISSUE THREAD

**Issue by TheRasPiGuy** [Times-0/Timeline#34]
Clicking the "Play CPPS" button takes me to a blank page with "Relogin the game" in the top left, and nothing else. It asked me for permission to use Flash the first time, but it doesn't do anything anymore

EDIT: Forgot to mention, there are no errors in my browsers console

**Comment by valid22** [comment]
This has to do less with Timeline but the media-server/html play page. Manually allow flash by going to site settings.

**Comment by TheRasPiGuy** [comment]
> This has to do less with Timeline but the media-server/html play page. Manually allow flash by going to site settings.

I've already don't this, but it still won't load, even though I used the Timeline template, and made sure to change everything to my domain name

**Comment by TheRasPiGuy** [comment]
EDIT: it's back to a blank screen

~~Update: It's still not loading fully, but it's now loading the background of the login screen, and thats it~~
![Screenshot_20](https://user-images.githubusercontent.com/17730905/89095859-86457a00-d386-11ea-9721-4ffa63836eec.png)

**Comment by TheRasPiGuy** [comment]
Still having the same issue, waiting for a response

**Comment by valid22** [comment]
This issue is in the wrong place and has nothing to do with timeline. Check your dev tools, you are probably missing swf files required to load.

**Comment by TheRasPiGuy** [comment]
I am using the swf file from skihill.net, which is redirected from icer.ink, and I am using your template that you provided

**Comment by valid22** [comment]
Open dev tools to check for missing swf.

**Comment by TheRasPiGuy** [comment]
I checked, and there are no errors in the console

**Comment by valid22** [comment]
Ping me on discord: valid22#0010
