### ISSUE TITLE
Assisting development

### ISSUE THREAD

**Issue by ghost** [Times-0/Timeline#35]
Hi, this isn't an issue but didn't know of a way to get in touch with you guys.

I've recently come across this project and I love what y'all are doing!

I used to code CPPS servers in PHP back in the prime days of the Rile5 forums. 2011-2015

I have had gotten redemption servers to fully work (Treasure Books, Golden Cards, DS game code, Campaign codes) and also game data saving and retrieving to work (Puffle Cannon uses this)
With a little luck I have found my old source files!

Would love to hear from you as I am not a highly proficient Python programmer but would really like to give my input :)

**Comment by valid22** [comment]
Discord: valid22#0010

**Comment by ghost** [comment]
Added you! (stefMT) also forgot to mention that I got puffles fully working, maybe I can help with some bugs
