### ISSUE TITLE
Two issues.

### ISSUE THREAD

**Issue by ghost** [Times-0/Timeline#38]
Hello, my name is Gabriel, and I'm having 2 issues:

# First
The first one is when i do "pyhton Flex.py". Here's a screenshot.
![image](https://user-images.githubusercontent.com/62163428/98667634-6a5e5680-232d-11eb-90b5-392cd315629f.png)
Traceback (most recent call last):
  File "flex.py", line 8, in <module>
    from Session import *
  File "C:\Users\henri\Desktop\TimeFlex-master\Session.py", line 3, in <module>
    from core import *
  File "C:\Users\henri\Desktop\TimeFlex-master\core.py", line 2, in <module>
    from flask_caching import Cache
  File "C:\Python27\lib\site-packages\flask_caching\__init__.py", line 412
    nonlocal source_check
                        ^
SyntaxError: invalid syntax

-----------------------------------
# Second
The second one is when i have already started "start.py" at timeline master, and I try to go to "play.localhost". I just get to this screen: 
![image](https://user-images.githubusercontent.com/62163428/98668230-5bc46f00-232e-11eb-8fb6-d4e79aea0002.png)
Then, i go to the "Play" folder and i asks me to enable flash player and I just get a white screen:
![image](https://user-images.githubusercontent.com/62163428/98668352-83b3d280-232e-11eb-874d-9e95b168a4a9.png)
When I go to the developer console, i got an error:
![image](https://user-images.githubusercontent.com/62163428/98668473-b4940780-232e-11eb-9963-85114889ce69.png)

-----------------------------------
(I'm running XAMPP, Apache, MYSQL, and started "Start.py").
-----------------------------------
# Thanks/other
Sorry for bad english (I'm from Brazil)
Sorry for bringing problems to you....
Thanks for making a CPPS Emulator, u're making many people happy!
Any help is welcome. Thanks.
If anyone needs any more screenshots, let me know.

**Comment by valid22** [comment]
For the first one, I suggest you to uninstall flash-caching (`pip uninstall flask-caching`) and install version 1.7.2 instead (`pip install Flask-Caching==1.7.2`)

For the second issue, make sure you have media-server, especially apache virtual hosts and subdomain setup as described in the docs - https://times-0.github.io/docs/mediaserver.html#AS3

**Comment by ghost** [comment]
# About the first issue
Thanks, you resolved it :D
# About the second issue:
I downloaded the micro version of the mediaserver, because i got an error when I tryed to download the full version 
![image](https://user-images.githubusercontent.com/62163428/98748198-f2794600-2397-11eb-9e41-73ca1eb60a68.png)
------------------------------
And for the part of the virtual hosts, I done some changes to the VHosts file and now I got a blue screen at play.localhost...
Screenshot: 
![image](https://user-images.githubusercontent.com/62163428/98749860-56e9d480-239b-11eb-8290-67a28622e961.png)


Anything more to do????
Thanks... :)
