### ISSUE TITLE
error msql pool

### ISSUE THREAD

**Issue by rafael01010** [Times-0/Timeline#43]
im error in start .py 
pls help 
out this
 INFO     | Starting MySQL DB Pool... @root:timeline
  ERROR    | Unable to start MySQL Pool on given details. (E:global name 'cpps' is not defined)
  INFO     | Unable to setup MySQL Pool

**Comment by valid22** [comment]
Did you make any changes to `Database/__init__.py` and Start.py?

**Comment by rafael01010** [comment]
> Did you make any changes to `Database/__init__.py` and Start.py?

I will put as login credentials i have same error 
this https://github.com/Times-0/Timeline/issues/6

**Comment by rafael01010** [comment]
im see this error

**Comment by rafael01010** [comment]
Error executing method - setSensei : an integer is required[exceptions.TypeError: an integer is required in File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__]
*--- Failure #9 ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:501: errback(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:568: _startRunCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:654: _runCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1475: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:22: setSensei(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:102: checkForSensei(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:250: inContext(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:266: <lambda>(...)
C:\Python27\lib\site-packages\twisted\python\context.py:122: callWithContext(...)
C:\Python27\lib\site-packages\twisted\python\context.py:85: callWithContext(...)
C:\Python27\lib\site-packages\twistar\dbconfig\mysql.py:26: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:460: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:36: __init__(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:76: reconnect(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:427: connect(...)
C:\Python27\lib\site-packages\MySQLdb\__init__.py:81: Connect(...)
C:\Python27\lib\site-packages\MySQLdb\connections.py:193: __init__(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
exceptions.TypeError: an integer is required
*--- End of Failure #9 ---
[WS:Tifani] (Redis) Setup memcache data successful!
[WS:Gravity] (Redis) Setup memcache data successful!
Error executing method - setSensei : an integer is required[exceptions.TypeError: an integer is required in File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__]
*--- Failure #14 ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:501: errback(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:568: _startRunCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:654: _runCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1475: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:33: setSensei(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Database\DB.py:267: db_init(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:250: inContext(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:266: <lambda>(...)
C:\Python27\lib\site-packages\twisted\python\context.py:122: callWithContext(...)
C:\Python27\lib\site-packages\twisted\python\context.py:85: callWithContext(...)
C:\Python27\lib\site-packages\twistar\dbconfig\mysql.py:26: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:460: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:36: __init__(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:76: reconnect(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:427: connect(...)
C:\Python27\lib\site-packages\MySQLdb\__init__.py:81: Connect(...)
C:\Python27\lib\site-packages\MySQLdb\connections.py:193: __init__(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
exceptions.TypeError: an integer is required
*--- End of Failure #14 ---
Error executing method - setSensei : an integer is required[exceptions.TypeError: an integer is required in File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__]
*--- Failure #16 ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:501: errback(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:568: _startRunCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:654: _runCallbacks(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1475: gotResult(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
--- <exception caught here> ---
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Handlers\Games\CardJitsu\CardJitsu.py:33: setSensei(...)
C:\Python27\lib\site-packages\twisted\internet\defer.py:1416: _inlineCallbacks(...)
C:\Python27\lib\site-packages\twisted\python\failure.py:512: throwExceptionIntoGenerator(...)
C:\Users\rafae\Desktop\Timeline-master\Timeline\Database\DB.py:267: db_init(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:250: inContext(...)
C:\Python27\lib\site-packages\twisted\python\threadpool.py:266: <lambda>(...)
C:\Python27\lib\site-packages\twisted\python\context.py:122: callWithContext(...)
C:\Python27\lib\site-packages\twisted\python\context.py:85: callWithContext(...)
C:\Python27\lib\site-packages\twistar\dbconfig\mysql.py:26: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:460: _runInteraction(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:36: __init__(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:76: reconnect(...)
C:\Python27\lib\site-packages\twisted\enterprise\adbapi.py:427: connect(...)
C:\Python27\lib\site-packages\MySQLdb\__init__.py:81: Connect(...)
C:\Python27\lib\site-packages\MySQLdb\connections.py:193: __init__(...)
 [Capture of Locals and Globals disabled (use captureVars=True)]
exceptions.TypeError: an integer is required
*--- End of Failure #16 ---

**Comment by rafael01010** [comment]
its new error

**Comment by rafael01010** [comment]
im fix this isse thx
