### ISSUE TITLE
change name blizzard world

### ISSUE THREAD

**Issue by rafael01010** [Times-0/Timeline#44]
im questing possiblity create new world blizzar and change name

**Comment by valid22** [comment]
To run a new server, go to [Start.py Line 228](https://github.com/Times-0/Timeline/blob/master/Start.py#L228), create a new server

```py
Blizzard = Engine(Penguin, Constants.WORLD_SERVER, 100, "Blizzard", server_protocol=Constants.CROSS_PROTOCOL)
Blizzard.run("", 9876)
SERVERS += [Blizzard]
```

That is all that is required to do in Timeline. You must further edit the client to add a new server connecting to this port.

**Comment by rafael01010** [comment]
ok thx
