### ISSUE TITLE
Black play page

### ISSUE THREAD

**Issue by rafael01010** [Times-0/Timeline#45]
hello im new issue im trying play cpps 
httpd-vhost.conf
![image](https://user-images.githubusercontent.com/67513151/130345796-5a26062b-8455-4bd8-a940-f7bb321665cb.png)

console error

![image](https://user-images.githubusercontent.com/67513151/130345809-4cc1c8d7-f902-44d4-b2fb-fa0929722bc6.png)

**Comment by valid22** [comment]
It shouldn't be happening in localhost. You can try some chrome extension which bypass CORS, also flash is no more supported in browsers, so you must be using a downloadable client.

**Comment by rafael01010** [comment]
im use flash extension but could you tell me a flash client

**Comment by rafael01010** [comment]
![image](https://user-images.githubusercontent.com/67513151/130346670-3c30e11c-d05c-4b1b-a8f2-f3fa8bf75701.png)
In chorme use flash this 
@valid22

**Comment by rafael01010** [comment]
im fix this intall this browser and flash 
https://www.youtube.com/watch?v=4u4JRm-x8GM

**Comment by rafael01010** [comment]
thx for help
