### ISSUE TITLE
Small login issue

### ISSUE THREAD

**Issue by Luke53** [Times-0/Timeline#8]
Hi.
Looks like a small logic error on line 87 of Login.py

87:  exist = (yield client.db_penguinExists('username', user)) if user != '$fire' and FIREBASE_INIT else True

This throws error from DB.py as it stills try to login even with an invalid penguin name.
If username !='$fire' and FIREBASE_INIT then is firebase is not initialised we will get 0 on this condition and set exist to true.

Can easily be fixed with:

exist = (yield client.db_penguinExists('username', user)) if (user != '$fire' and FIREBASE_INIT == 0) else True

**Comment by valid22** [comment]
Thanks for pointing this out! Kudos to you. I'll bring out a fix and update you soon.

**Comment by valid22** [comment]
Ref, https://github.com/Times-0/Timeline/commit/bdac71254aabffc43c11bc2d3d4ae3eee8387161

Hope that helps.

**Comment by Luke53** [comment]
That fixes is. Also quick question did you ever have a glitch with the skate-park lines with testing? I made a server side fix when i was messing around with kitsune but I feel like it is my client.
Also great work this CPPS source looks really great.

**Comment by valid22** [comment]
I did experience it during early stages of production, never experienced it then after

**Comment by Luke53** [comment]
Must be something with my client then because it still occurs with different server sources. Thanks anyway.

**Comment by valid22** [comment]
It could still potentially be a server issue idk, I'll check and confirm later, mainly because I was able to fix it before by tweaking server.  I doubt if other sources knew that thing was supposed to be implemented on server.
Anyway, marking this issue as fixed.

**Comment by Luke53** [comment]
@valid22 Sorry to bug you again but is there a reason why EPF features were removed? Was it broken?

**Comment by valid22** [comment]
Not broken, I don't see the point of having it :male_shrug:
It was meaningful when it had missions, but CP itself abandoned it for years. Only reason to have it was because of its teleportation, but that can be achieved via !jr command.

Still it's just disabled, you can tweak some comments to bring it back alive

**Comment by Luke53** [comment]
Okay thanks
