### ISSUE TITLE
Unable to login penguin into Server

### ISSUE THREAD

**Issue by YouYouTheBoxx** [Times-0/Timeline#9]
Hello, i can't connect to the server. My penguin gets disconnect by this error : 
 '' ERROR    | [WS:Gravity] <Penguin #1 on 3724>, AS3p need more than 1 value to unpack ''

Here is the full trace log :
  DEBUG    | [WS:Gravity] [SEND] <Penguin #0 on 3724>, AS3p <cross-domain-policy><allow-access-from domain='*' to-ports='3724' /></cross-domain-policy>
  DEBUG    | [WS:Gravity] [RECV] <Penguin #0 on 3724>, AS3p <policy-file-request/>
  DEBUG    | [WS:Gravity] [SEND] <Penguin #0 on 3724>, AS3p <cross-domain-policy><allow-access-from domain='*' to-ports='3724' /></cross-domain-policy>
  INFO     | [WS:Gravity] <Penguin #0 on 3724>, AS3p Disconnected Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
  INFO     | [WS:Gravity] Built new protocol for user#0
  DEBUG    | [WS:Gravity] [SEND] <Penguin #1 on 3724>, AS3p <cross-domain-policy><allow-access-from domain='*' to-ports='3724' /></cross-domain-policy>
  DEBUG    | [WS:Gravity] [RECV] <Penguin #1 on 3724>, AS3p <msg t='sys'><body action='verChk' r='0'><ver v='153' /></body></msg>
  DEBUG    | [WS:Gravity] [SEND] <Penguin #1 on 3724>, AS3p <msg t="sys"><body action="apiOK" r="0"/></msg>
  DEBUG    | [WS:Gravity] [RECV] <Penguin #1 on 3724>, AS3p <msg t='sys'><body action='rndK' r='-1'></body></msg>
  DEBUG    | [WS:Gravity] [SEND] <Penguin #1 on 3724>, AS3p <msg t="sys"><body action="rndK" r="-1"><k><![CDATA[>v$WJ-4U'2]]></k></body></msg>
  DEBUG    | [WS:Gravity] [RECV] <Penguin #1 on 3724>, AS3p <msg t='sys'><body action='login' r='0'><login z='w1'><nick><![CDATA[Younesarc2]]></nick><pword><![CDATA[dcdb3546b8b92c228c26f4390802e7c6]]></pword></login></body></msg>
  ERROR    | [WS:Gravity] <Penguin #1 on 3724>, AS3p need more than 1 value to unpack
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  INFO     | Penguin ASync-Refresh-ing : Penguin - $Ensei, Forced - False
  WARNING  | Discarding Penguin<AS3p> Object: <Penguin #0 on 3724> : <Penguin #0 on 3724>, AS3p
  INFO     | [WS:Gravity] <Penguin #1 on 3724>, AS3p Disconnected Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
  WARNING  | Discarding Penguin<AS3p> Object: <Penguin #1 on 3724> : <Penguin #1 on 3724>, AS3p

**Comment by valid22** [comment]
You are not helping me by removing all the necessary packet transfers.
```
ERROR | [WS:Gravity] <Penguin #1 on 3724>, AS3p need more than 1 value to unpack
```
That raised due to some malformed packet sent by the client. 

It won't be of any help, unless you are willing to show the complete detailed log.

**Comment by Luminatrixx** [comment]
Thanks for the reply and sorry for removed necessary packet transfers. Github cuts off some of the packets transfers because it seems like some of them are code used by it.

The full log is here : 
[LogFile.txt](https://github.com/Times-0/Timeline/files/2934998/LogFile.txt)

**Comment by valid22** [comment]
From what I can infer, it seems you have swapped servers. You have probably made the login server (port) the actual world server, and world server the login server.

Check both your client and Timeline if the ports exactly match and doesn't conflict with each other.

**Comment by Luminatrixx** [comment]
Thanks. That was the problem but now when i enter a server it says incorrect password : case sensitive. What to do ?
Here's full log :
[LogFile.txt](https://github.com/Times-0/Timeline/files/2935376/LogFile.txt)

**Comment by valid22** [comment]
Try again. Check if it persists. (Make sure you don't take more than 15 mins to choose a server)

**Comment by Luminatrixx** [comment]
Yes it persist with same error. The problem is that this is happening only when i'm choosing a server even if i take only 2 seconds to choose one. What can be the cause of this ? : 
[LogFile.txt](https://github.com/Times-0/Timeline/files/2935429/LogFile.txt)

**Comment by valid22** [comment]
Can you send over your start.py.(If you have your mysql username password, and vps ip remove those and send)

**Comment by Luminatrixx** [comment]
Yes sure. Here it is : (.txt file because github don't support uploading .py)
[Start.txt](https://github.com/Times-0/Timeline/files/2935513/Start.txt)

**Comment by valid22** [comment]
Did you try to login to Gravity. Please cross check the ports in client with one in that file. If you are not using AS2, running as2 servers are unnecessary. Make sure there world server are AS3 and not AS2

**Comment by Luminatrixx** [comment]
Yes, i tried to login to Gravity and my world server is AS3.

**Comment by valid22** [comment]
Contact me on discord `valid22#1856`

**Comment by valid22** [comment]
Seemed to be an issue with the version of `redis` that doesn't accept expire-time as a parameter.

**Comment by MartinYAY** [comment]
Hi. I'm having this exact same error. How do I fix it?

**Comment by valid22** [comment]
> Hi. I'm having this exact same error. How do I fix it?

@MartinYAY please create a new issue, attach your log file with it (./logs/Timeline.log). Make sure redis is running.
